apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - prometheusrule-taskfarm.yaml
  - ingress-grafana.yaml
  - ingress-argocd.yaml

# patches:
#   - path: hpa-patch.yaml
#     target:
#       group: autoscaling
#       version: v2
#       kind: HorizontalPodAutoscaler
#       name: taskfarm-user
