apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-slack
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: taskfarm-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: alertmanager-slack
    creationPolicy: Owner
  data:
    - secretKey: slack-webhook-url
      remoteRef:
        key: team4/taskfarm/prod/alertmanager-slack
        property: webhook-url
