apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: taskfarm-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-admin
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: team4/taskfarm/prod/grafana-admin
        property: admin-user
    - secretKey: admin-password
      remoteRef:
        key: team4/taskfarm/prod/grafana-admin
        property: admin-password
