apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: taskfarm-user
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: taskfarm-user
  minReplicas: 1
  maxReplicas: 3 # dev는 작게. prod overlay에서 키울 수 있음
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  # 스케일링 속도 제어
  behavior:
    scaleUp:
      # 부하 증가 시 빠르게 반응
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Max

    scaleDown:
      # 부하가 줄어도 바로 줄이지 않고 5분 동안 안정화 => 트래픽이 잠깐 줄었다고 Pod를 바로 줄이는 것을 방지
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Min
