apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - externalsecret-alertmanager-slack.yaml
  - externalsecret-grafana.yaml
  - servicemonitor-user.yaml
  - servicemonitor-admin.yaml
  - overlays/prod

configMapGenerator:
  - name: taskfarm-grafana-dashboards
    files:
      - dashboards/grafana-dashboard-taskfarm.json
      - dashboards/grafana-dashboard-jvm-micrometer.json
      - dashboards/grafana-dashboard-springboot-apm.json
    options:
      labels:
        grafana_dashboard: "1"
      disableNameSuffixHash: true
