apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: taskfarm-user-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: taskfarm-secret-store
    kind: SecretStore
  target:
    name: taskfarm-user-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef: { key: team4/taskfarm/dev/db, property: username }
    - secretKey: DB_PASSWORD
      remoteRef: { key: team4/taskfarm/dev/db, property: password }
    - secretKey: JWT_SECRET
      remoteRef: { key: team4/taskfarm/dev/jwt-secret }
    - secretKey: GEMINI_API_KEY
      remoteRef: { key: team4/taskfarm/dev/gemini-api-key }
