apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: taskfarm-dev
resources:
- ../../base
- namespace.yaml
- secretstore.yaml
- externalsecret.yaml
  # ⚠️ ingress 없음 (dev=port-forward)
patches:
- path: patch-dev.yaml
  target:
    kind: Deployment
    name: taskfarm-user
images:
- name: taskfarm-user-img
  newName: 194722398200.dkr.ecr.ap-northeast-2.amazonaws.com/team4-dev-taskfarm-user
  newTag: dev-98ba9b2
configMapGenerator:
- behavior: merge
  literals:
  - SPRING_PROFILES_ACTIVE=dev,worker
  - DB_HOST=PLACEHOLDER-dev-rds-endpoint
  - REDIS_HOST=PLACEHOLDER-dev-redis-endpoint
  name: taskfarm-user-config
