apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: taskfarm-admin-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: taskfarm-admin-secret-store
    kind: SecretStore
  target:
    name: taskfarm-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef: { key: team4/taskfarm/dev/db, property: username }
    - secretKey: DB_PASSWORD
      remoteRef: { key: team4/taskfarm/dev/db, property: password }
    - secretKey: JWT_SECRET
      remoteRef: { key: team4/taskfarm/dev/jwt-secret }
