apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: taskfarm-admin
    newName: 000000000000.dkr.ecr.ap-northeast-2.amazonaws.com/team4-dev-taskfarm-admin
    newTag: dev

patches:
  - path: patch-dev.yaml

configMapGenerator:
  - name: taskfarm-admin-config
    behavior: merge
    literals:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=team4-dev-rds.endpoint.replace-me
      - DB_REPLICA_HOST=team4-dev-rds.endpoint.replace-me

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app.kubernetes.io/environment: dev
