apiVersion: v1
kind: ConfigMap
metadata:
  name: taskfarm-admin-config
data:
  DB_PORT: "3306"
  DB_NAME: "taskfarm"
  REDIS_PORT: "6379"
  REDIS_SSL_ENABLED: "false"
  JPA_DDL_AUTO: "validate"
  AWS_REGION: "ap-northeast-2"
  SERVER_SERVLET_CONTEXT_PATH: "/admin"

  MFA_KMS_ENABLED: "true"
  MFA_KMS_KEY_ID: "arn:aws:kms:ap-northeast-2:194722398200:key/01860773-78d4-4ef8-9f7a-24acbe66c538"