apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: taskfarm-admin-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: team4-secrets-manager
    kind: ClusterSecretStore
  target:
    name: taskfarm-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: /team4/taskfarm/admin
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /team4/taskfarm/admin
        property: DB_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: /team4/taskfarm/admin
        property: JWT_SECRET
