apiVersion: v1
kind: Service
metadata:
  name: taskfarm-admin
  labels:
    app.kubernetes.io/name: taskfarm-admin
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: taskfarm-admin
  ports:
    - name: http
      port: 80
      targetPort: 8081
