apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: taskfarm-admin-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: taskfarm-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: taskfarm-admin-secret
    creationPolicy: Owner
  data:
    # prod 경로
    - secretKey: DB_USERNAME
      remoteRef: { key: team4/taskfarm/prod/db, property: username }
    - secretKey: DB_PASSWORD
      remoteRef: { key: team4/taskfarm/prod/db, property: password }
    - secretKey: JWT_SECRET
      remoteRef: { key: team4/taskfarm/prod/jwt-secret }
