apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: taskfarm-prod
resources:
- ../../base
- externalsecret.yaml
- ingress.yaml
patches:
- path: patch-prod.yaml
  target:
    kind: Deployment
    name: taskfarm-admin
images:
- name: taskfarm-admin-img
  newName: 194722398200.dkr.ecr.ap-northeast-2.amazonaws.com/team4-prod-taskfarm-admin
  newTag: prod-fddf1db
configMapGenerator:
- behavior: merge
  literals:
  - SPRING_PROFILES_ACTIVE=prod
  name: taskfarm-admin-config
