apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: taskfarm-prod
resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml
patches:
  - path: patch-prod.yaml
    target:
      kind: Deployment
      name: taskfarm-admin
images:
  - name: taskfarm-admin-img
    newName: 194722398200.dkr.ecr.ap-northeast-2.amazonaws.com/team4-prod-taskfarm-admin
    newTag: latest
configMapGenerator:
  - name: taskfarm-admin-config
    behavior: merge
    literals:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=PLACEHOLDER-prod-rds-endpoint
      - REDIS_HOST=PLACEHOLDER-prod-redis-endpoint
