apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskfarm-admin
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: taskfarm-admin
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
