apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskfarm-admin-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CLD-05/team4-taskfarm-config.git
    targetRevision: main
    path: manifests/admin/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: taskfarm-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
