apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskfarm-root-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CLD-05/team4-taskfarm-config.git
    targetRevision: main
    path: apps
    directory:
      recurse: false
      include: '{user-prod.yaml,admin-prod.yaml,monitoring-prod.yaml}'   # prod + monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
