{
 "title": "Falco Security Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "syscall 처리율\t",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(falcosecurity_scap_n_evts_total[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "룰별 탐지",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (rule_name)(falcosecurity_falco_rules_matches_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU/Memory\t사용량",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "falcosecurity_falco_cpu_usage_ratio",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "falcosecurity_falco_memory_rss_bytes",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "이벤트 유실",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "falcosecurity_scap_n_drops_total",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}