apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: taskfarm-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: taskfarm-secret-store
    kind: SecretStore
  target:
    name: taskfarm-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: /taskfarm/dev/db/username

    - secretKey: DB_PASSWORD
      remoteRef:
        key: /taskfarm/dev/db/password

    - secretKey: JWT_SECRET
      remoteRef:
        key: /taskfarm/dev/jwt/secret

    - secretKey: REDIS_USERNAME
      remoteRef:
        key: /taskfarm/dev/redis/username

    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: /taskfarm/dev/redis/password
