apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: taskfarm-prod
resources:
- ../../base
- secretstore.yaml
- externalsecret.yaml
- ingress.yaml
patches:
- path: patch-prod.yaml
  target:
    kind: Deployment
    name: taskfarm-user
images:
- name: taskfarm-user-img
  newName: 194722398200.dkr.ecr.ap-northeast-2.amazonaws.com/team4-prod-taskfarm-user
  newTag: prod-10b1b63
configMapGenerator:
- behavior: merge
  literals:
  - SPRING_PROFILES_ACTIVE=prod,worker
  name: taskfarm-user-config
